# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - |

      # Automatically update the content from the `dist/` directory
      $(npm bin)/commit-changes --branch "master" \
                                --commands "npm run build" \
                                --commit-message "Update content from the \`dist\` directory [skip ci]"

env:
  global:

    # The `secure` key contains three encrypted environment variables
    # (GH_TOKEN, GH_USER_EMAIL and GH_USER_NAME), the values of which
    # are used by the scripts that are automatically executed by Travis.
    #
    # Note: The `secure` key will only work for this repository, so if
    # you create your own fork, you will need to generate your own key:
    #
    #   travis encrypt -r "<username>/<repository>" \
    #     GH_TOKEN="<your_github_access_token>" \
    #     GH_USER_EMAIL="<your_email>" \
    #     GH_USER_NAME="<your_name>"
    #
    # To learn more about how to generate the:
    #
    #   * `secure` key, see:
    #     http://docs.travis-ci.com/user/encryption-keys/
    #
    #   * GitHub access token, see:
    #     https://help.github.com/articles/creating-an-access-token-for-command-line-use/

    - secure: "OQnRHkXKdvSujTPm0DSXJFrso0zKltkso0e8zF/2GLI7ouv60ELHhYCrWFuoeefSJFbiPeH/9GXnTAv7y+gC08Ba/DSlXGaHl4db5xU/7AazzQR4YaTks6z0CfvlftdlimGOY27tuDU8hMfqHJKybJGcEvFKCVJms/7udYYh+CA="

git:
  depth: 10

language: node_js

node_js:
  - "0.12"
  - "4"

sudo: false
